// <auto-generated />
namespace Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Create_FooterSlider : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_FooterSlider));
        
        string IMigrationMetadata.Id
        {
            get { return "202001161313064_Create_FooterSlider"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
