// <auto-generated />
namespace Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class update_fs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_fs));
        
        string IMigrationMetadata.Id
        {
            get { return "202001161317428_update_fs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
